export type PracticalReaction = readonly [english: string, japanese: string];

export const practicalReactionSets = [
  [['Pretty good too, thanks.', 'こっちもけっこういいよ、ありがとう。'], ['I hope it calms down soon.', '早く落ち着くといいね。'], ['I’m glad you have a little time to breathe now.', '今は少しゆっくりできてよかった。']],
  [['Okay, I’ll see you in a bit.', '了解。じゃあ、またあとで。'], ['Sure—one latte.', 'もちろん。ラテを一つね。'], ['Yep, I’ll grab that for you.', 'うん、買っていくね。']],
  [['No problem.', '大丈夫だよ。'], ['Thanks—I’ll text you when I’m close.', 'ありがとう。近くなったら連絡するね。'], ['Perfect, thanks for doing that.', '助かる。ありがとう。']],
  [['Let’s try the place next door.', '隣の店に行ってみよう。'], ['Okay, we can wait a bit.', '分かった。少し待とう。'], ['Good idea. I’ll ask how long it’ll be.', 'いいね。どのくらいか聞いてみる。']],
  [['Then let’s get something to eat.', 'じゃあ、何か食べよう。'], ['Nice. I still need to eat.', 'いいね。私はまだ食べてないんだ。'], ['You must be hungry. Let’s find something now.', 'お腹すいたでしょ。今から何か探そう。']],
  [['Lucky you—mine’s been busy.', 'いいな。こっちは忙しいよ。'], ['Same here. Hopefully it stays manageable.', 'こっちも同じ。手に負えるくらいだといいね。'], ['That sounds exhausting. Hope you can finish soon.', 'それは大変そう。早く終わるといいね。']],
  [['Walking might be faster at this point.', 'もう歩いたほうが早いかもね。'], ['The bus is probably your best bet.', 'バスが一番よさそう。'], ['Let me know which route works—I’m still checking too.', 'どのルートで行けたか教えて。こっちもまだ調べてる。']],
  [['Good—you came prepared.', 'よかった、ちゃんと持ってきたんだね。'], ['Yeah, there are a few shops nearby.', 'うん、近くに店がいくつかあるよ。'], ['Of course. We can share mine.', 'もちろん。私の傘に入って。']],
  [['Got it—just milk.', '了解。牛乳だけね。'], ['Sure, I’ll get eggs and bread too.', 'もちろん。卵とパンも買うね。'], ['Perfect. I’ll see what fruit looks good.', '了解。よさそうな果物を見てみるね。']],
  [['I’m in. What are you in the mood for?', '賛成。何が食べたい？'], ['That might be quicker.', 'そのほうが早いかもね。'], ['Good call. I’ll pull up the menu.', 'それがいいね。メニューを開くよ。']],
  [['The pasta looked good.', 'パスタ、おいしそうだった。'], ['Take your time—I’m still deciding too.', 'ゆっくりでいいよ。私もまだ迷ってる。'], ['Good idea. I think they can make it mild.', 'いいね。甘口にできると思うよ。']],
  [['Great—that makes choosing a place easy.', 'よかった。店を選びやすいね。'], ['Thanks for telling me. We’ll avoid seafood.', '教えてくれてありがとう。魚介は避けよう。'], ['Got it. We’ll find somewhere with milder options.', '了解。辛くない料理がある店を探そう。']],
  [['Sure, let’s do that.', 'うん、そうしよう。'], ['Deal—I’ll get the next one.', '決まり。次は私が払うね。'], ['That’s easy enough. Let’s split it that way.', 'それが分かりやすいね。そうしよう。']],
  [['Maybe we can make a plan.', 'じゃあ何か予定を立てようか。'], ['Nice. Hope you two have fun.', 'いいね。楽しんできて。'], ['Sunday could work for me too.', '私も日曜日なら空いてるかも。']],
  [['Great. I’ll send you the details.', 'よかった。詳細を送るね。'], ['We’re meeting around seven.', '7時ごろに集まるよ。'], ['I’ll send the address. Join us whenever you can.', '住所を送るね。間に合うときに来て。']],
  [['Great, Sunday it is.', 'よかった。日曜日にしよう。'], ['The afternoon works for me too.', '私も午後で大丈夫。'], ['Lunch works. How about noon?', 'お昼で大丈夫。12時はどう？']],
  [['Same—I haven’t found much lately.', '私も。最近あまり見つからない。'], ['What’s it called?', '何ていうドラマ？'], ['Send me the title. I’ll add it to my list.', 'タイトルを送って。リストに入れておく。']],
  [['Sending it now.', '今送るね。'], ['I think this one will be right up your alley.', 'これはたぶん好みに合うと思う。'], ['I hope it makes your commute a little better.', '通勤が少し楽しくなるといいな。']],
  [['Text works for me.', 'メッセージで大丈夫。'], ['Okay, I’ll call after six.', '分かった。6時過ぎに電話するね。'], ['Sounds good. I’ll text you first.', '了解。最初にメッセージするね。']],
  [['Thanks for understanding.', '分かってくれてありがとう。'], ['Yeah, things got unexpectedly busy.', 'うん、急に忙しくなっちゃって。'], ['Everything’s okay. Sorry I made you worry.', '大丈夫だよ。心配させてごめんね。']],
  [['Oh, got it—you’re free tomorrow.', 'ああ、分かった。明日は空いてるんだね。'], ['Tomorrow works better for me too.', '私も明日のほうが都合いいよ。'], ['Thanks for repeating that. After work tomorrow works.', 'もう一度言ってくれてありがとう。明日の仕事後で大丈夫。']],
  [['Thanks.', 'ありがとう。'], ['That’s much easier to follow.', 'そのほうがずっと聞き取りやすい。'], ['Perfect. I’ll ask if I miss anything.', '助かる。聞き取れなかったら聞くね。']],
  [['Good—I’m glad you’re on board.', 'よかった。賛成してくれてうれしい。'], ['That’s fair. Let’s give ourselves more time.', '確かに。もう少し時間を取ろう。'], ['I agree. Next week gives us room to do it properly.', '同感。来週ならきちんと進める余裕があるね。']],
  [['Thanks. I’ll keep it brief.', 'ありがとう。手短に話すね。'], ['I appreciate that. Here’s how I see it.', 'ありがとう。私にはこう見えてる。'], ['That’s all I’m asking. Let me explain what concerns me.', 'それで十分。何が気になっているか説明するね。']],
  [['Thanks for understanding.', '分かってくれてありがとう。'], ['I appreciate it. Yesterday got away from me.', 'ありがとう。昨日は余裕がなくて。'], ['Thanks. I should have sent a quick message sooner.', 'ありがとう。もっと早く一言送るべきだった。']],
  [['Of course.', 'もちろん。'], ['Anytime—I’m glad it helped.', 'いつでも。役に立ててよかった。'], ['I know you would. Just ask whenever you need me.', 'あなたもそうしてくれるよね。必要なときはいつでも言って。']],
  [['I’ll send you the details.', '詳しい内容を送るね。'], ['Sure. I’ll explain what I need.', '分かった。何をお願いしたいか説明するね。'], ['After dinner is perfect. I’ll message you now.', '夕食後でちょうどいい。今メッセージするね。']],
  [['Thanks—I really appreciate it.', 'ありがとう。本当に助かる。'], ['Sure, I’ll show you what to check.', 'うん、確認してほしいところを見せるね。'], ['That would take a lot off my plate. Thank you.', 'それだと負担がかなり減る。ありがとう。']],
  [['Great, thank you.', 'よかった。ありがとう。'], ['I’ll send the final details today.', '今日中に最終の詳細を送るね。'], ['That works. Keep me posted if anything changes.', 'それで大丈夫。何か変わったら知らせて。']],
  [['Tomorrow morning works. How about ten?', '明日の朝で大丈夫。10時はどう？'], ['Two-thirty works for me.', '2時半なら大丈夫。'], ['Perfect. I’ll send an invite for three.', 'ちょうどいい。3時で招待を送るね。']],
  [['Glad to hear it.', 'それはよかった。'], ['That sounds like a good reset.', 'いい気分転換になったみたいだね。'], ['You probably needed that quiet Sunday.', '何もしない日曜日が必要だったんだね。']],
  [['Yeah, let’s go.', 'うん、行こう。'], ['Same. I’ve been staring at this screen too long.', '私も。画面を長く見すぎた。'], ['No rush. I’ll meet you by the door in five.', '急がなくていいよ。5分後にドアのところで会おう。']],
  [['Yeah, I’m here. What happened?', 'うん、いるよ。何があった？'], ['Of course. Take your time.', 'もちろん。ゆっくりでいいよ。'], ['We can do whichever feels easier for you.', 'あなたが楽なほうでいいよ。']],
  [['Really? What happened?', '本当？何があったの？'], ['Tell me everything.', '全部聞かせて。'], ['I’m listening—start from the beginning.', '聞くよ。最初から話して。']],
  [['Nice. How are they doing?', 'いいね。みんな元気？'], ['That’s good. I’m sure they were happy to hear from you.', 'よかった。きっと電話を喜んだね。'], ['You should call tonight. I’m sure they’d love to hear from you.', '今夜電話したら。きっと喜ぶよ。']],
  [['That café would be perfect.', 'あのカフェがぴったりだね。'], ['That sounds like a solid plan.', 'それ、いいプランだね。'], ['I like that. It keeps the day flexible.', 'いいね。そのほうが一日を柔軟に過ごせる。']],
  [['Sure, I’ll send them now.', 'もちろん。今送るね。'], ['No problem. I’ll include a map link.', '大丈夫。地図のリンクも付けるね。'], ['Perfect. I’ll send everything before you leave.', '了解。出発前に全部送っておくね。']],
  [['It’s no trouble. I’ll meet you there.', '全然大変じゃないよ。駅で会おう。'], ['Not at all. Just text me when you arrive.', '全然大丈夫。着いたらメッセージして。'], ['Okay, that works too. I’ll wait near my place.', '分かった。それでも大丈夫。家の近くで待ってるね。']],
  [['You still have time.', 'まだ時間はあるよ。'], ['That location will be convenient.', 'その場所なら便利だね。'], ['Good plan. Send me the name once you book it.', 'いいね。予約したら名前を送って。']],
  [['Okay, let’s check the later flight.', '分かった。遅い便を確認しよう。'], ['Good idea. I’ll ask about other routes.', 'いいね。ほかのルートを聞いてみる。'], ['Agreed. Let’s compare the arrival times first.', '同感。まず到着時間を比べよう。']],
  [['Good—I’m glad it was easy.', 'よかった。簡単にできたんだね。'], ['Ah, that’s annoying. Can you go back tomorrow?', 'ああ、それは面倒だね。明日また行けそう？'], ['Nice. Hopefully the next place has your size.', 'よかった。次の店にサイズがあるといいね。']],
  [['I’ll check downstairs.', '下を確認してみる。'], ['I’ll ask next door.', '隣の人に聞いてみる。'], ['Good idea. I’ll check the photo before I contact them.', 'いいね。連絡する前に写真を確認する。']],
  [['Great—Tuesday should work.', 'よかった。火曜日なら大丈夫そう。'], ['Hopefully they get back to you soon.', '早く返事が来るといいね。'], ['At least you got a new time without canceling.', 'キャンセルせず別の時間にできてよかったね。']],
  [['Thanks. I’m going to sleep for a while.', 'ありがとう。しばらく寝るよ。'], ['I will. Thanks for checking on me.', 'そうする。気にかけてくれてありがとう。'], ['That means a lot. I’ll let you know if I need anything.', 'そう言ってくれてうれしい。必要なものがあったら連絡するね。']],
  [['Sorry about that.', 'ごめんね。'], ['I didn’t realize it carried through the wall.', '壁越しに聞こえるとは思わなかった。'], ['Absolutely. I’ll turn it down much earlier next time.', 'もちろん。次からはもっと早い時間に音を下げるね。']],
  [['A walk sounds perfect.', '散歩、ちょうどいいね。'], ['I’m up for that. I can bring something to cook.', 'いいね。料理するものを持っていくよ。'], ['That actually sounds like a really fun night.', 'それ、実際かなり楽しい夜になりそう。']],
  [['Okay, I wasn’t sure if you had.', 'よかった。見たか分からなかった。'], ['It was even better in person.', '実際に見るともっとすごかったよ。'], ['I took it from the trail above the lake.', '湖の上にある遊歩道から撮ったんだ。']],
  [['Of course. We can take it easy.', 'もちろん。ゆっくりしよう。'], ['That’s exactly what I was hoping for.', 'まさにそうしたかった。'], ['Perfect. A quiet night sounds good.', 'いいね。静かな夜にしよう。']],
  [['Friday works for me.', '私は金曜日で大丈夫。'], ['How about Saturday afternoon?', '土曜の午後はどう？'], ['Saturday afternoon works. I’ll keep it open too.', '土曜の午後で大丈夫。私も空けておくね。']],
  [['Talk soon. Get home safe.', 'またね。気をつけて帰って。'], ['Same here. Let’s not wait so long next time.', '私も。次はこんなに間を空けないようにしよう。'], ['I will. I’ll text you later this week.', 'そうする。今週またメッセージするね。']],
] as const;
