export type ReciprocalTurn = readonly [
  questionEnglish: string | null,
  questionJapanese: string | null,
  answerEnglish: string,
  answerJapanese: string,
];

export const reciprocalTurns = [
  ['How has your day been?', 'そっちはどんな一日だった？', 'Not bad. I had a busy morning, but it’s calmed down now.', '悪くないよ。朝は忙しかったけど、今は落ち着いた。'],
  ['Could you make it oat milk?', 'オーツミルクにしてもらえる？', 'Sure—one oat-milk latte.', 'もちろん。オーツミルクのラテを一つね。'],
  ['Do you want me to order for you?', '先に注文しておこうか？', 'Yes, please. Just get me an iced tea.', 'お願い。アイスティーだけ頼んでおいて。'],
  ['Do you know how long the wait is?', '待ち時間がどのくらいか分かる？', 'They said about fifteen minutes.', '15分くらいだって。'],
  ['Have you eaten yet?', 'そっちはもう食べた？', 'Not yet. Let’s find something together.', 'まだ。一緒に何か探そう。'],
  ['How’s your day going?', 'そっちは今日どう？', 'Busy too, but I should be done on time.', 'こっちも忙しいけど、時間どおりには終われそう。'],
  ['What are you going to do?', 'そっちはどうするの？', 'I might take the bus too. The train isn’t moving at all.', '私もバスにするかも。電車が全然動いてない。'],
  ['Did you bring one?', 'そっちは傘持ってきた？', 'Yeah, I have one. We can share if you need to.', 'うん、持ってる。必要なら一緒に入れるよ。'],
  ['Do you want anything else?', 'ほかに必要なものある？', 'No, that’s everything. Thanks for checking.', 'ううん、それで全部。聞いてくれてありがとう。'],
  ['What are you in the mood for?', '何が食べたい気分？', 'Maybe Thai food. We haven’t had it in a while.', 'タイ料理かな。しばらく食べてないし。'],
  ['What are you getting?', 'そっちは何にするの？', 'Probably the curry. It looks really good.', 'たぶんカレー。すごくおいしそう。'],
  ['Is that okay with you?', 'それでも大丈夫？', 'Of course. We’ll pick somewhere with plenty of other options.', 'もちろん。ほかの料理がたくさんある店を選ぼう。'],
  ['Does that work for you?', 'それで大丈夫？', 'Yep, that works. I’ll get the next one.', 'うん、大丈夫。次は私が払うね。'],
  ['What about you?', 'そっちは？', 'I don’t have anything planned yet.', '私はまだ何も予定を入れてないよ。'],
  [null, null, 'We’re meeting around seven at the place near the station.', '駅の近くの店に7時ごろ集まるよ。'],
  ['What time works for you?', '何時が都合いい？', 'How about two? That gives us plenty of time.', '2時はどう？それなら時間に余裕がある。'],
  ['Do you think I’d like it?', '私も気に入りそう？', 'I think so. Send me the title and I’ll take a look.', 'たぶんね。タイトルを送ってくれたら見てみる。'],
  ['What have you been listening to lately?', '最近は何を聴いてる？', 'Mostly my old playlists. I need something new too.', 'ほとんど昔のプレイリスト。私も新しい曲が欲しい。'],
  ['Does six-thirty work?', '6時半で大丈夫？', 'Six-thirty is perfect. I’ll call you then.', '6時半でちょうどいい。その時間に電話するね。'],
  ['Is everything okay?', '何かあった？大丈夫？', 'Yeah, everything’s fine. Work just got unexpectedly busy.', 'うん、大丈夫。仕事が急に忙しくなっただけ。'],
  ['What time works for you?', '何時が都合いい？', 'Any time after six works for me.', '6時以降ならいつでも大丈夫。'],
  ['Was that clear?', '今のは分かりやすかった？', 'Yes, much clearer. Thanks.', 'うん、ずっと分かりやすかった。ありがとう。'],
  ['Can we look at it again next week?', '来週もう一度見直せる？', 'Absolutely. Let’s put some time aside on Monday.', 'もちろん。月曜日に時間を取ろう。'],
  ['What concerns you most?', '一番気になっているのは何？', 'Mostly the timing. I think we’re trying to move too fast.', '主にタイミングかな。少し急ぎすぎていると思う。'],
  ['Is everything okay now?', '今はもう大丈夫？', 'Yeah, it is. Thanks for asking.', 'うん、もう大丈夫。聞いてくれてありがとう。'],
  ['Did everything work out?', 'そのあと、うまくいった？', 'It did. We finished everything before the deadline.', 'うまくいったよ。締め切り前に全部終わった。'],
  [null, null, 'I need help moving a table. It should only take a few minutes.', 'テーブルを動かすのを手伝ってほしい。数分で終わると思う。'],
  [null, null, 'Yeah, I’ll send you the document now.', 'うん、今その書類を送るね。'],
  ['Can you send them before lunch?', 'お昼までに送ってもらえる？', 'Yes, I’ll send everything by eleven.', 'うん、11時までに全部送るよ。'],
  ['Would two-thirty work?', '2時半で大丈夫？', 'Two-thirty works. I’ll send a calendar invite.', '2時半で大丈夫。カレンダーの招待を送るね。'],
  ['How was yours?', 'そっちはどうだった？', 'Good. I went for a hike on Sunday.', 'よかったよ。日曜日にハイキングへ行った。'],
  ['Want to grab a coffee while we’re out?', '外に出たついでにコーヒーも買う？', 'Sure. I could use one.', 'いいね。ちょうど飲みたかった。'],
  ['Is it work?', '仕事のこと？', 'Yeah. A project went wrong, and I’m not sure how to fix it yet.', 'うん。プロジェクトがうまくいかなくて、まだ直し方が分からない。'],
  [null, null, 'I got the job I interviewed for last week.', '先週面接を受けた仕事に受かったんだ。'],
  ['How’s everyone doing?', 'みんな元気にしてる？', 'They’re doing well. My sister just started a new job.', 'みんな元気だよ。妹が新しい仕事を始めたばかり。'],
  ['Which restaurant would you pick?', 'レストランならどこを選ぶ？', 'There’s a new place downtown that would be fun to try.', '街中に新しい店があるから、行ってみると楽しそう。'],
  ['Could you send a map pin too?', '地図のピンも送ってもらえる？', 'Of course. I’ll send the pin with the directions.', 'もちろん。道順と一緒にピンも送るね。'],
  ['What time should I arrive?', '何時に着けばいい？', 'Around noon would be perfect.', 'お昼ごろがちょうどいい。'],
  ['Have you heard of it?', 'そのホテル、聞いたことある？', 'Yeah, a friend stayed there and said it was clean and quiet.', 'うん、友だちが泊まって、清潔で静かだったと言ってた。'],
  ['Can you check the train options?', '電車の選択肢を調べてくれる？', 'Sure. I’ll compare the times while you check the flights.', 'もちろん。そっちが便を調べている間に時間を比べるね。'],
  ['Do you think they’ll accept a photo of it?', 'レシートの写真でも受け付けてくれると思う？', 'Maybe. It’s worth calling before you go back.', 'たぶん。戻る前に電話してみる価値はあるね。'],
  ['Could you ask next door?', '隣の人に聞いてくれる？', 'Yeah, I’ll ask them now.', 'うん、今聞いてみる。'],
  ['Should I call them tomorrow?', '明日こちらから電話したほうがいいかな？', 'Yes. If they don’t reply today, I’d call in the morning.', 'うん。今日返事がなければ、朝に電話したほうがいい。'],
  ['Can I check on you later?', 'あとでまた連絡してもいい？', 'Please do. I’ll probably be awake this evening.', 'お願い。夕方にはたぶん起きてる。'],
  ['Could you turn it down after ten?', '10時を過ぎたら音を下げてもらえる？', 'Absolutely. I’m sorry it kept you up.', 'もちろん。眠れなくさせてごめん。'],
  ['What should we watch?', '何を見ようか？', 'How about a comedy? I could use something light.', 'コメディはどう？気軽に見られるものがいいな。'],
  ['When did you go?', 'いつ行ったの？', 'Last weekend. The weather was perfect.', '先週末。天気が最高だった。'],
  ['Want me to bring some food?', '何か食べ物を持っていこうか？', 'Yes, please. Something simple would be great.', 'お願い。簡単なもので十分。'],
  ['Does Saturday afternoon work?', '土曜の午後で大丈夫？', 'Saturday afternoon works for me.', '土曜の午後で大丈夫。'],
  ['Can you text me when you get home?', '家に着いたらメッセージしてくれる？', 'Of course. I’ll let you know when I’m home.', 'もちろん。着いたら連絡するね。'],
] satisfies readonly ReciprocalTurn[];
